[package]
name = "book-batch-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
config = "0.15.11"
diesel = { version = "2.2.9", features = ["postgres"] }
serde = { version = "1.0.219", features = ["derive"] }
